### ISSUE TITLE
Desenvolvimento página de seleção de usuário para avaliação

### ISSUE THREAD

**Issue by isadorarocsilva** [Pythonators/API_semestre1_pythonators#11]
Antes de comecar a codar, eu criei todo o wireframe do projeto no figma. Para essa pagina especifica (Selecao de usuario para avaliacao) eu importei tudo do figma para o python utilizando o Tkinter.

O tkinter gera um código não totalmente válido para o front-end tornando necessario posteriormente alguns ajustes de posicionamento das features.

**Comment by flpcsr** [comment]
Antes de comecar a codar, eu criei todo o wireframe do projeto no figma. Para essa pagina especifica (Selecao de usuario para avaliacao) eu importei tudo do figma para o python utilizando o Tkinter.

O tkinter gera um código não totalmente válido para o front-end tornando necessario posteriormente alguns ajustes de posicionamento das features.

**Comment by CSous-a** [comment]
após desenvolvimento de sprint 2, foi decidido que a seleção de usuario seria diferente, tendo abas de navegação com base em nome de participantes
