### ISSUE TITLE
Realizar a ligação das páginas de Login, Seleção de Sprint, Seleção de Usuário para avaliar e de Avaliação

### ISSUE THREAD

**Issue by Cauana** [Pythonators/API_semestre1_pythonators#18]
Realizar a ligação das páginas de Login, Seleção de Sprint, Seleção de Usuário para avaliar e de Avaliação.

- Descobrir a melhor forma de linkar as páginas. Seja por toplevel, por import e destroy ou por thread.
- Linkar as páginas e excluir a anterior.
- Ir de uma página a outra sem quebrar as imagens.

**Comment by CSous-a** [comment]
refazer fluxo para = Login -> tela de usuario -> seleção de sprint -> tela de avaliação (ou revisão, ou gráficos de acompanhamento)
