### ISSUE TITLE
Elaboração das questões com base na avaliação likert

### ISSUE THREAD

**Issue by anadamascenos** [Pythonators/API_semestre1_pythonators#2]
Foram elaboradas 5 perguntas levando em consideração os softskils e hábilidades técnicas, tanto levando em conta conhecimentos prévios, quanto desejo em aprender, uma vez que houveram participantes que ingressaram totalmente novos na área, tendo que desenvolver seu entendimento do zero.

As perguntas foram: 

O avaliado fez entregas pontualmente

O avaliado fez entregas de acordo com as propostas da sprint

O avaliado teve um bom desempenho no trabalho em equipe

O avaliado demonstrou habilidades e/ou desejo em se desenvolver nas tecnologias usadas no projeto

O avaliado teve uma comunicação clara com o grupo quanto às suas dificuldades e evoluções no decorrer das sprints

**Comment by CSous-a** [comment]
possivelmente o professor nadalete irá nos dar essas avaliações posteriormente, como tópicos de softskills, como foi dado na sprint 1 avaliação
