### ISSUE TITLE
correção de bug : avaliação

### ISSUE THREAD

**Issue by CSous-a** [Pythonators/API_semestre1_pythonators#35]
Ao finalizar avaliação está ocorrendo um bug, que leva a uma página de erro, ao invés de levar até a visualização de avaliação ou confirmação de finalização de avaliação.

**Comment by CSous-a** [comment]
![Image](https://user-images.githubusercontent.com/111454312/194438236-ee8262cf-326d-4c4c-953c-ccc84bd75ba4.png)

**Comment by CSous-a** [comment]
criar uma tela de feedback pós avaliação, onde é necessário terminar de preencher, uma vez que o erro se trata de uma ausência de avaliação.

**Comment by Marcelofbd** [comment]
Feito a tratativa do erro de avaliação, agora não é mais permitido enviar avaliação com sem terminar de preencher a mesma
