### ISSUE TITLE
modelagem do banco de dados

### ISSUE THREAD

**Issue by CSous-a** [Pythonators/API_semestre1_pythonators#44]
Criação e atualização das estocagens:
- Turma (sala);
- Time;
- Aluno;
- Professor;
- Avaliação; (atualizar)
- Herança: banco geral num único arquivo JSON -> USUÁRIO

**Comment by MikaelaBgtt** [comment]
Segue abaixo o esboço da modelagem em JSON:

[diagrama_modelo_esboçado.pptx](https://github.com/Pythonators/API_semestre1_pythonators/files/9882860/diagrama_modelo_esbocado.pptx)
