### ISSUE TITLE
Criação de um banco de dados para as avaliações

### ISSUE THREAD

**Issue by isadorarocsilva** [Pythonators/API_semestre1_pythonators#9]

**Comment by Cauana** [comment]
- Modelagem de tabela em planilha no Excel;
- Obtenção de dados enviados através do formulário, utilizando os valores do radiobutton.

**Comment by Cauana** [comment]
- Modelagem de tabela em planilha no Excel;
- Obtenção de dados enviados através do formulário, utilizando os valores do radiobutton.
